import { StyleSheet } from 'react-native';
import { useMemo } from 'react';
import { useTheme, lightColors } from './theme';
export function useStyles() { const { C } = useTheme(); return useMemo(() => makeStyles(C), [C]); }
// 排版与形状刻度沿用课表应用的体系：
// 字距随字号变化（大标题负字距），行距与字号反比，层级由字重＋字号＋行距共同构建；
// 圆角分控件 12、输入 14、卡片 18、面板 20、弹层 28；间距取 4 的倍数，页边距 20、卡片内边距 16。
const makeStyles = (C: typeof lightColors) => StyleSheet.create({
  attachmentGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 },
  attachmentTile: { width: '31%', aspectRatio: 1, borderRadius: 12, overflow: 'hidden', backgroundColor: C.wash },
  attachmentImage: { width: '100%', height: '100%' },
  removeAttachment: { position: 'absolute', top: 0, right: 0, width: 36, height: 36, alignItems: 'center', justifyContent: 'center', backgroundColor: '#00000088', borderBottomLeftRadius: 12 },
  audioAttachment: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  root: { flex: 1, backgroundColor: C.paper },
  shell: { flex: 1, width: '100%', maxWidth: 620, alignSelf: 'center' },
  loading: { flex: 1, justifyContent: 'center', padding: 32, gap: 24 },
  logo: { fontSize: 40, color: C.ink },
  top: {
    paddingHorizontal: 20,
    height: 64,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderColor: C.line,
  },
  brand: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  brandMark: { width: 5, height: 22, backgroundColor: C.accent, borderRadius: 16 },
  brandText: { fontSize: 22, fontWeight: '700', letterSpacing: 2, color: C.ink },
  page: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 112 },
  eyebrow: { fontSize: 12, color: C.muted, lineHeight: 18, letterSpacing: 0.2 },
  headingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 28,
  },
  heading: {
    fontSize: 30,
    fontWeight: '600',
    lineHeight: 40,
    letterSpacing: -0.5,
    color: C.ink,
    marginTop: 8,
    marginBottom: 12,
  },
  dateStamp: { alignItems: 'center', borderLeftWidth: 1, borderColor: C.line, paddingLeft: 16 },
  dateNumber: { fontSize: 35, color: C.accent, fontWeight: '300', fontVariant: ['tabular-nums'] },
  meta: { fontSize: 12, color: C.muted, lineHeight: 18 },
  capture: { backgroundColor: C.wash, padding: 20, borderRadius: 20, marginBottom: 28 },
  captureText: { fontSize: 18, lineHeight: 28, color: C.muted, minHeight: 52 },
  captureBottom: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 16,
  },
  capturePlus: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: C.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inline: { flexDirection: 'row', alignItems: 'center', gap: 8, flexWrap: 'wrap' },
  actionRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  sectionHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
    marginTop: 4,
  },
  sectionTitle: { fontSize: 16, fontWeight: '600', lineHeight: 22, letterSpacing: -0.2, color: C.ink },
  filters: { gap: 12, paddingBottom: 12 },
  filter: { paddingVertical: 8, borderBottomWidth: 2, borderBottomColor: 'transparent' },
  filterActive: { borderBottomColor: C.accent },
  filterText: { fontSize: 13, lineHeight: 20, color: C.muted },
  memory: {
    flexDirection: 'row',
    gap: 16,
    padding: 16,
    marginBottom: 12,
    borderRadius: 18,
    backgroundColor: C.wash,
    borderWidth: 1,
    borderColor: C.line,
  },
  memoryDate: { width: 32, alignItems: 'center' },
  day: { fontSize: 26, fontWeight: '300', color: C.ink, fontVariant: ['tabular-nums'] },
  memoryContent: { flex: 1 },
  memoryMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  memoryText: { fontSize: 16, lineHeight: 28, color: C.ink, marginBottom: 8 },
  previewPhoto: { width: '100%', height: 156, marginTop: 8, marginBottom: 8, borderRadius: 14 },
  endMark: { alignItems: 'center', marginTop: 36 },
  shortLine: { width: 20, height: 1, backgroundColor: C.line },
  footnote: { fontSize: 12, lineHeight: 20, color: C.muted, marginTop: 12, marginBottom: 8 },
  // 悬浮毛玻璃底栏：脱离文档流悬浮于内容之上，滚动内容从其下方穿过。
  // 圆角取高度的一半，两端呈正圆。
  navGlass: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 8,
    borderRadius: 31,
    overflow: 'hidden',
    borderWidth: 1,
  },
  nav: {
    flexDirection: 'row',
    paddingTop: 6,
    paddingBottom: 4,
    backgroundColor: 'transparent',
  },
  navItem: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingBottom: 6, gap: 4, minHeight: 52 },
  navText: { fontSize: 12, color: C.muted },
  search: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: C.wash,
    paddingHorizontal: 16,
    borderRadius: 14,
    marginTop: 12,
    marginBottom: 28,
  },
  searchInput: { flex: 1, fontSize: 15, lineHeight: 22, paddingVertical: 16, color: C.ink },
  askPanel: {
    padding: 20,
    borderRadius: 20,
    backgroundColor: C.wash,
    marginBottom: 28,
  },
  description: { fontSize: 14, lineHeight: 23, color: C.muted, marginTop: 8, marginBottom: 16 },
  question: {
    minHeight: 100,
    fontSize: 16,
    lineHeight: 26,
    color: C.ink,
    textAlignVertical: 'top',
    paddingTop: 8,
    paddingBottom: 16,
  },
  body: { fontSize: 16, lineHeight: 28, color: C.ink },
  answer: { paddingVertical: 20 },
  source: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, paddingVertical: 8 },
  sourceNumber: { color: C.accent, fontSize: 12, lineHeight: 20 },
  sourceText: { fontSize: 12, lineHeight: 20, color: C.muted, flex: 1 },
  profileIntro: { fontSize: 14, lineHeight: 23, color: C.muted, marginTop: 0, marginBottom: 24 },
  insight: { paddingVertical: 20 },
  insightLine: { borderBottomWidth: 1, borderColor: C.line },
  rule: { height: 1, backgroundColor: C.line, marginVertical: 20 },
  pickRow: { flexDirection: 'row', gap: 12, paddingVertical: 14, alignItems: 'flex-start' },
  pickBox: { width: 22, height: 22, borderRadius: 11, borderWidth: 1.5, borderColor: C.line, alignItems: 'center', justifyContent: 'center', marginTop: 2 },
  pickAll: { alignSelf: 'flex-start' },
  dot: { width: 5, height: 5, borderRadius: 3, backgroundColor: C.green },
  insightText: { fontSize: 18, lineHeight: 30, color: C.ink, marginTop: 8, marginBottom: 12 },
  pending: { backgroundColor: C.wash, padding: 20, borderRadius: 18, marginBottom: 20 },
  small: { fontSize: 13, color: C.ink, lineHeight: 21 },
  toast: {
    position: 'absolute',
    bottom: 100,
    alignSelf: 'center',
    backgroundColor: C.ink,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 20,
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  sheetShell: { flex: 1, width: '100%', maxWidth: 620, alignSelf: 'center' },
  sheetHeader: {
    height: 64,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderColor: C.line,
  },
  sheetBody: { padding: 20, paddingBottom: 48, backgroundColor: C.paper },
  editor: {
    fontSize: 18,
    lineHeight: 30,
    color: C.ink,
    minHeight: 180,
    textAlignVertical: 'top',
    paddingTop: 24,
    paddingBottom: 20,
  },
  category: { paddingHorizontal: 12, paddingVertical: 10, borderRadius: 12 },
  detailText: { fontSize: 21, lineHeight: 36, color: C.ink, marginVertical: 24 },
  detailPhoto: { width: '100%', height: 260, marginVertical: 8, borderRadius: 14 },
  audio: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    padding: 16,
    backgroundColor: C.wash,
    borderRadius: 14,
    marginVertical: 8,
  },
  audioLine: { height: 1, backgroundColor: C.line, marginTop: 8 },
  recording: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 20 },
  history: { borderTopWidth: 1, borderColor: C.line, paddingTop: 20, marginTop: 24 },
  settingsTitle: { fontSize: 26, fontWeight: '600', lineHeight: 34, letterSpacing: -0.4, color: C.ink, marginTop: 20 },
  field: {
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 14,
    padding: 14,
    fontSize: 14,
    lineHeight: 21,
    color: C.ink,
    backgroundColor: C.paper,
  },
  settingsGroup: { padding: 20, borderRadius: 20, backgroundColor: C.wash, marginBottom: 20, gap: 12 },
  feedback: { padding: 16, borderRadius: 14, backgroundColor: C.accentLight, marginVertical: 12, gap: 4 },
  demo: {
    backgroundColor: C.accentLight,
    paddingVertical: 8,
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  demoText: { fontSize: 11, lineHeight: 16, color: C.accentDark },
  noticeOverlay: { flex: 1, backgroundColor: '#00000066', justifyContent: 'center', padding: 28 },
  notice: {
    backgroundColor: C.paper,
    padding: 24,
    borderRadius: 20,
    width: '100%',
    maxWidth: 450,
    alignSelf: 'center',
  },
});
