const { chromium, expect } = require('@playwright/test');
const fs = require('node:fs');
const path = require('node:path');
(async () => {
  const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true,
    args: ['--use-fake-device-for-media-stream', '--use-fake-ui-for-media-stream'] });
  const context = await browser.newContext({ viewport: { width: 393, height: 852 }, permissions: ['microphone'] });
  const page = await context.newPage();
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  page.on('dialog', () => { throw Error('Unexpected native dialog'); });
  const out = path.resolve(__dirname, '../../artifacts/v0.3.0'); fs.mkdirSync(out, { recursive: true });
  const button = name => page.getByRole('button', { name, exact: true });
  const field = name => page.getByLabel(name, { exact: true });
  await page.goto('http://127.0.0.1:4173');
  await button('设置').click();
  await button('深色').click();
  await expect.poll(() => page.evaluate(() => localStorage.getItem('zixu.appearance'))).toBe('dark');
  await page.waitForTimeout(450);
  await page.screenshot({ path: path.join(out, 'settings-dark.png') });
  await button('浅色').click();
  await field('API Key').fill('fake-deepseek-key');
  await field('模型名称').fill('model-a');
  await button('Kimi').click();
  await expect(field('API Key')).toHaveValue('');
  await field('API Key').fill('fake-kimi-key');
  await field('模型名称').fill('model-b');
  await button('DeepSeek').click();
  await expect(field('API Key')).toHaveValue('fake-deepseek-key');
  await expect(field('模型名称')).toHaveValue('model-a');
  await button('Kimi').click();
  await expect(field('API Key')).toHaveValue('fake-kimi-key');
  await expect(field('模型名称')).toHaveValue('model-b');
  await button('自定义兼容接口').click();
  await field('API 地址（以 /v1 等服务商路径结尾）').fill('https://interaction-test.invalid/v1');
  await field('API Key').fill('fake-custom-key');
  await field('模型名称').fill('test-model');
  let status = 200;
  await page.route('https://interaction-test.invalid/v1/chat/completions', r => r.fulfill({ status,
    contentType: 'application/json', body: JSON.stringify({ choices: [{ message: { content: 'OK' } }] }) }));
  await button('测试连接').click();
  await expect(page.getByText('连接成功', { exact: true })).toBeVisible();
  status = 401;
  await button('测试连接').click();
  await expect(page.getByText('连接失败', { exact: true })).toBeVisible();
  await expect(page.getByText('Key 未通过验证，请检查设置。', { exact: true })).toBeVisible();
  await page.waitForTimeout(450);
  await page.screenshot({ path: path.join(out, 'connection-failure.png') });
  await button('保存设置').click();
  await button('返回').click();
  await button('设置').click();
  await expect(field('API Key')).toHaveValue('fake-custom-key');
  await button('跟随系统').click();
  await page.emulateMedia({ colorScheme: 'dark' });
  await expect(button('跟随系统')).toBeVisible();
  await button('返回').click();
  await page.reload();
  await button('设置').click();
  await expect.poll(() => page.evaluate(() => localStorage.getItem('zixu.appearance'))).toBe('system');
  await button('浅色').click();
  await button('返回').click();
  await button('记一条').click();
  await field('记录内容').fill('今天想给自己留一点安静的时间。');
  await button('开始录音').click();
  await button('暂停').click();
  await expect(button('继续录音')).toBeVisible();
  await expect(button('保存')).toBeDisabled();
  await button('继续录音').click();
  await expect(button('暂停')).toBeVisible();
  await page.waitForTimeout(1200);
  await button('完成录音').click();
  await expect(button('播放录音')).toBeVisible();
  await expect(field('记录内容')).toBeVisible();
  await field('记录内容').fill('今天想给自己留一点安静的时间。录完再补一句。');
  await expect(button('添加照片')).toBeVisible();
  await page.waitForTimeout(450);
  await page.screenshot({ path: path.join(out, 'composer-finished-audio.png') });
  await button('保存').click();
  await page.getByRole('button', { name: /打开记录：今天想/ }).click();
  await button('修改').click();
  await field('记录内容').fill('今天留下一段语音，也补上了文字。');
  await button('保存').click();
  await expect(button('修改')).toBeVisible();
  // 修改前的文字现在是折叠触发，展开后应显示修订前的原文。
  await page.getByRole('button', { name: /修改前的文字/ }).click();
  await expect(page.getByText('今天想给自己留一点安静的时间。录完再补一句。', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: /收起修改前的文字/ }).click();
  await button('删除').click();
  await expect(page.getByText('删除这条记录？', { exact: true })).toBeVisible();
  await page.waitForTimeout(450);
  await page.screenshot({ path: path.join(out, 'dialog-light.png') });
  await button('取消').click();
  await expect(button('修改')).toBeVisible();
  await button('返回').click();
  await page.waitForTimeout(450);
  await page.screenshot({ path: path.join(out, 'records-light.png') });
  await page.setViewportSize({ width: 320, height: 640 });
  await button('设置').click();
  await page.waitForTimeout(450);
  await page.screenshot({ path: path.join(out, 'settings-320.png') });
  if (errors.length) throw Error(errors.join('\n'));
  console.log('PASS: theme persistence, system mode, isolated provider profiles, explicit connection feedback, pause/resume/finish recording, continued editing, detail return, styled cancellation, narrow layout.');
  await browser.close();
})().catch(e => { console.error(e); process.exit(1); });
